import { Injectable } from '@nestjs/common';
import ExcelJS from 'exceljs';
import type { ScorecardPayload } from './compliance-scorecard.service';

@Injectable()
export class ExcelExportService {
    async buildComplianceScorecardWorkbook(params: {
        payload: ScorecardPayload;
        contentHash: string;
        verificationUrl: string;
        documentId: string;
        generatedAt: Date;
    }): Promise<Buffer> {
        const { payload, contentHash, verificationUrl, documentId, generatedAt } = params;
        const wb = new ExcelJS.Workbook();
        wb.creator = 'GovLink';
        wb.created = generatedAt;

        const ws = wb.addWorksheet('Compliance Scorecard');
        ws.views = [{ state: 'frozen', ySplit: 1 }];
        ws.columns = [
            { header: 'PSGC Code', key: 'psgc', width: 14 },
            { header: 'Barangay', key: 'barangay', width: 28 },
            { header: 'Code', key: 'requirementCode', width: 10 },
            { header: 'Requirement', key: 'requirement', width: 36 },
            { header: 'Period', key: 'periodLabel', width: 14 },
            { header: 'Due Date', key: 'dueDate', width: 14 },
            { header: 'Status', key: 'status', width: 14 },
            { header: 'Pass/Fail', key: 'passFail', width: 12 },
            { header: 'Days Overdue', key: 'daysOverdue', width: 14 },
        ];

        const headerRow = ws.getRow(1);
        headerRow.font = { bold: true };
        headerRow.fill = {
            type: 'pattern',
            pattern: 'solid',
            fgColor: { argb: 'FFE2E8F0' },
        };
        headerRow.alignment = { vertical: 'middle' };
        ws.autoFilter = { from: 'A1', to: 'I1' };

        for (const row of payload.rows) {
            ws.addRow(row);
        }

        const log = wb.addWorksheet('Audit Log');
        const fields: [string, string][] = [
            ['Report Type', 'Compliance Scorecard'],
            ['Generated At', this.formatManila(generatedAt)],
            ['Generated By', payload.generatedBy.fullName],
            ['Role', payload.generatedBy.roles.join(', ')],
            ['Municipality', `Municipality of ${payload.municipality.name}`],
            ['Province', `Province of ${payload.municipality.province}`],
            ['Period', payload.periodLabel ?? 'All open periods'],
            ['Record Count', String(payload.rows.length)],
            ['Export Document ID', documentId],
            ['Content Hash', contentHash],
            ['Verification URL', verificationUrl],
            ['GovLink Version', process.env.npm_package_version ?? '0.1.0'],
        ];
        fields.forEach(([k, v], i) => {
            log.getCell(`A${i + 1}`).value = k;
            log.getCell(`A${i + 1}`).font = { bold: true };
            log.getCell(`B${i + 1}`).value = v;
        });
        log.getColumn(1).width = 22;
        log.getColumn(2).width = 56;

        const legend = wb.addWorksheet('Legend');
        legend.addRow(['Pass/Fail', 'Meaning']);
        legend.addRow(['PASS', 'Accepted / compliant']);
        legend.addRow(['PENDING', 'Not started, in progress, or submitted (not yet due as fail)']);
        legend.addRow(['FAIL', 'Overdue or returned for correction']);
        legend.addRow([]);
        legend.addRow(['Legal basis', 'RA 7160 general supervision; DILG MCs in requirement catalog']);
        legend.getRow(1).font = { bold: true };

        const arrayBuffer = await wb.xlsx.writeBuffer();
        return Buffer.from(arrayBuffer);
    }

    private formatManila(date: Date): string {
        return new Intl.DateTimeFormat('en-PH', {
            timeZone: 'Asia/Manila',
            year: 'numeric',
            month: '2-digit',
            day: '2-digit',
            hour: '2-digit',
            minute: '2-digit',
            second: '2-digit',
            hour12: false,
        }).format(date);
    }
}
